cookie:
  expiry_days: 30
  key: sdfasdfasf # Must be a string
  name: some_cookie_name
credentials:
  usernames:
    mauser:
      email: mauser@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Ma
      last_name: User
      logged_in: False # Will be managed automatically
      password: abc # Will be hashed automatically
    admin:
      email: admin@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: admin
      last_name: admin
      logged_in: False # Will be managed automatically
      password: password # Will be hashed automatically
